### ISSUE TITLE
followup with Dick at Gates re: CC0 for data as option within Open Access Policy

### ISSUE THREAD

**Issue by tvol** [creativecommons/foundation-policy-engagement#5]

**Comment by tvol** [comment]
@peterspdx is it my turn to followup with Dick?

**Comment by peterspdx** [comment]
sure, please do.  i'll make sure you have the last one I sent.

**Comment by tvol** [comment]
as discussed, we should just wait till when we reach out to them on the FSI project in order to expand their existing open access policy to a more general open policy.
