### ISSUE TITLE
prep CIFF program officer webinar

### ISSUE THREAD

**Issue by tvol** [creativecommons/foundation-policy-engagement#64]
based on https://docs.google.com/presentation/d/1U_epskUOnvRev7JfG1TdK-YJkOsSIpWLxGvYCActbnw/edit?usp=sharing

**Comment by cablegreen** [comment]
Great slides!  Feedback:
- slide 7: text too far to the left - can't see in presentation mode
- slide 14 - use updated chart from SOTC report - showing growth to 1.1B
- slide 34 - you might ask Hewlett to update: http://www.hewlett.org/creative-commons to CC BY 4.0 ... they do so in all of their grantee materials already // and then get a new screen shot ;)

**Comment by tvol** [comment]
https://docs.google.com/presentation/d/1XJcDXYKDCBYPdtqIB2hqjWXmaDeNnvWti-yxHDqD6OM/edit
